### ISSUE TITLE
Paths should only be added if they are not already in the PATH

### ISSUE THREAD

**Issue by chicks-net** [JanDeDobbeleer/aliae#140]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I just started playing with `aliae` and so I started converting some of my setup over.  When playing with the path feature I noticed that the resulting config will blindly add the new directories to the beginning of the `PATH`.  What if the directory was already in the `PATH`?  Wouldn't it be cool to check whether it was there first so you don't end up with duplicates and harder times debugging?

The concern I'm guessing you would have with adding this feature is that it would be difficult to get the shell syntax right for all of the different supported shells, but ideas like https://superuser.com/a/39780/358509 encourage me that there might be some portable solutions that would work for most POSIX environments.

My config is based on the sample config from the docs:

```
path:
  - value: |
      /opt/homebrew/bin/
      /opt/homebrew/sbin/
    if: match .OS "darwin"
  - value: |
      {{ .Home }}/.local/bin
      /usr/local/bin/
      {{ .Home }}/go/bin/
```

and running `aliae init zsh --config ./.aliae.yaml` gave me:

```
export PATH="/opt/homebrew/bin/:$PATH"
export PATH="/opt/homebrew/sbin/:$PATH"
export PATH="/Users/chicks/.local/bin:$PATH"
export PATH="/usr/local/bin/:$PATH"
export PATH="/Users/chicks/go/bin/:$PATH"
```

**Comment by JanDeDobbeleer** [comment]
@chicks-net this is already how we add to PATH. We check if that folder already exists, only prefix if it's not yet in there. Do you see a different behavior?

**Comment by chicks-net** [comment]
I do understand that you are verifying that the directory actually exists.  I found the bug about that earlier.  But I don't see anything that checks for whether the directory is already in the `PATH`. 

To create a simple example:
```
# prior
PATH="/opt/homebrew/bin/"
# from aliae config
export PATH="/opt/homebrew/bin/:$PATH"
# show result
echo "PATH=$PATH"
```

results in `PATH=/opt/homebrew/bin/:/opt/homebrew/bin/` .

**Comment by JanDeDobbeleer** [comment]
@chicks-net we have that logic built-in, we split on `:`, then check if the value we have is already in that array. I can validate if there's a bug here but we do have the intention to do what you want.

**Comment by JanDeDobbeleer** [comment]
I just ran a small test, did notice this can occur when the path has a trailing path separator, but your example doesn't indicate that:

<img width="867" alt="image" src="https://github.com/user-attachments/assets/66139361-3522-4efa-bb62-af6e3245cecd">

The trailing separator fix is incoming.

**Comment by chicks-net** [comment]
I see it now.  I had a trailing slash on the directory and I jumped to the wrong conclusion.  Thank you for your assistance.
