### ISSUE TITLE
fish Variables Are Not Set as Environment Variables

### ISSUE THREAD

**Issue by manuth** [JanDeDobbeleer/aliae#158]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When specifying `env` entries and loading the configuration into `fish` using the command
```
aliae init fish | source
```
the variables are only visible within `fish`, but not in sub-processes.

I assume, this is because variables are declared as `--global`s instead of `--export`. (Probably it should be both `--global` and `--export`?)

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

fish

**Comment by JanDeDobbeleer** [comment]
@manuth that's a good point. Allow me to add that.

**Comment by manuth** [comment]
Awesome! Thank you so much for the rapid answer 😄
