### ISSUE TITLE
Support including multiple alias files without overwriting

### ISSUE THREAD

**Issue by boldandbrad** [JanDeDobbeleer/aliae#191]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Before I get into it let me just say I love this tool and I think it has a lot of potential to help me wrangle my dotfiles and system configs. Thank you for building it!

## Problem

I have a *ton* of aliases in my dotfiles and I'd like to use aliae to help me manage them across shells and systems. BUT, cramming them all into a single `.aliae.yaml` file is both extremely verbose and a bit difficult to maintain. I'd like the ability to logically group them across different files or lists to make them easier to find and maintain. At first glance, `aliae`'s `include/_dir` functionality seems to be the perfect solve, but in practice it doesn't function they way I'd expect.

In short, I'd like to create an aliae setup that resembles something like the following:

```txt
.aliae.yaml
aliases/
  nav.yaml
  git.yaml
  go.yaml
  ...
```

Where `.aliae.yaml` looks like:

```yaml
aliae: !include_dir "./aliases"

# generic aliases
alias:
  - name: vim
    value: nvim

env:
  ...
```

And each of the files under `aliases/` contains a list of aliases to include, for example `nav.yaml`:

```yaml
alias:
  - name: ...
    value: cd ../..
  - name: apps
    value: cd ~/Applications
```

> As a side note, I've found that the [example in the docs](https://aliae.dev/docs/setup/include#example) isn't entirely correct, as the `alias:` tag needs to be present at the top of the included file in order for it be included correctly.

Today, the setup I've described above doesn't work. `aliae` *does* appear to properly read each of the included files, but does not concatenate their contents into a main list of aliases. Instead, the last `alias:` list read is the *only* one sourced. In the example above, that would be the one in `.aliae.yaml` since it is after the include statement. If `.aliae.yaml` didn't include its own list, the only one sourced would be `nav.yaml` since it is last alphanumerically in the aliases directory. This effectively renders to purpose of being able to import from other files useless.

## Proposal

My ask is that all of the included alias lists are either all independently sourced or concatenated into a main list that is sourced all at once. Obviously there might need to be a check for duplicate names, but that problem is not unique to this approach.

I'd expect the env/script segments to work the same way, though I haven't tested them out myself.

Thanks for the consideration!

**Comment by JanDeDobbeleer** [comment]
@boldandbrad this is a really good idea! I'm going to give aliae some love next week as I've been so busy with oh-my-posh the past months.

**Comment by boldandbrad** [comment]
Awesome!! 🙌

To go even further, might be cool to be able to apply an `if` directive to the include so that you can conditionally include a whole file or directory instead of applying duplicate`if` conditions to a bunch of records that all rely on the same condition.

This could be done by either applying the `if` to the include or by putting a global if at the top of the included file or `alias:` list. Not sure which approach is more flexible.

**Comment by JanDeDobbeleer** [comment]
> As a side note, I've found that the [example in the docs](https://aliae.dev/docs/setup/include#example) isn't entirely correct, as the alias: tag needs to be present at the top of the included file in order for it be included correctly.

@boldandbrad this doesn't seem to be true anymore, but I did have to rework this due to a breaking change in the yaml parser.

**Comment by boldandbrad** [comment]
Can't wait to try this out. Thank you so much!
