### ISSUE TITLE
init in pwsh profile throws error

### ISSUE THREAD

**Issue by DavidDeSloovere** [JanDeDobbeleer/aliae#2]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Thanks for starting this great project. Couldn't wait and had to try it out already. Being early adopter I ran into this issue.

After adding `aliae init pwsh | Invoke-Expression` to the powershell profile (as per docs) I get the following error:
`Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.`

I also have `oh-my-posh init pwsh --config "~/.mytheme.omp.json" | Invoke-Expression` in my profile, and that works without a problem 😉. 

Running `aliae init pwsh | Invoke-Expression` in terminal (powershell) returns the same error.

Running `aliae init pwsh` returns `(@(& aliae init pwsh --config= --print) -join "``n") | Invoke-Expression`. With a single "`", just markdown issues here in GH.

PowerShell 7.3.5

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@DavidDeSloovere I'll check this evening. Have to admit I validated on macOS using core, will run a few checks cross platform as well.

**Comment by DavidDeSloovere** [comment]
Looks like v0.1.1 is not  ID10T proof yet :-)
I had created a YAML, but it was empty.
Following the instructions, you start with the installation and init. And later there'a page on the config.

**Comment by JanDeDobbeleer** [comment]
I was aware of this gap, changing the order definitely is a good idea though! I want to create a nice CLI to easily add aliases as well.
