### ISSUE TITLE
Invalid argument starting on powershell

### ISSUE THREAD

**Issue by Dominiquini** [JanDeDobbeleer/aliae#20]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tried starting this application on "powershell", but this message appears:

Command: `aliae init powershell | Invoke-Expression`

Message:
```
Error: invalid argument "powershell" for "aliae init"
Usage:
  aliae init [bash|zsh|fish|powershell|pwsh|cmd|nu|tcsh|xonsh] --config ~/.aliae.yaml [flags]

Flags:
  -h, --help    help for init
  -p, --print   print the init script

Global Flags:
  -c, --config string   config file path
```

Looks like "powershell" is a invalid argument, but the help message lists it like was valid!

Thanks.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@Dominiquini that's because it needs to be `pwsh`, not `powershell`.
