### ISSUE TITLE
incorrect yaml multiline string handling

### ISSUE THREAD

**Issue by harrhp** [JanDeDobbeleer/aliae#210]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

consider config like this
```
alias:
  - name: s
    value: >
      !f() {
        set -e -o pipefail;
        git status;
      };
      f
    type: git
```

`>` supposed to replace new lines with spaces (https://yaml-multiline.info/). instead it keeps new lines

git config before 0.23

```
[alias]
	s = "!f() {   set -e -o pipefail;   git status; }; f"
```

after
```
[alias]
	s = "!f() {\n  set -e -o pipefail;\n  git status;\n}; f\n"
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
Seems to be due to an upgrade in the yaml parser (which looks like a bug there).

```diff
- github.com/goccy/go-yaml v1.12.0
+ github.com/goccy/go-yaml v1.14.3
```
