### ISSUE TITLE
Auto create missing directories when symlinking

### ISSUE THREAD

**Issue by boldandbrad** [JanDeDobbeleer/aliae#227]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Problem

Currently, given a file tree like:

```txt
~/.config/
    foo/foo.conf
```

And an aliae.yaml like:

```yaml
link:
  - name: ~/.config/bar/bar.conf
    target: path/to/bar.conf
```

Upon shell startup the following error will be produced:

`ln: .../.config/bar/bar.conf: No such file or directory`

This is because ln cannot create a symbolic link in the `bar` directory since it doesn't exist.

### Solution

It might be nice to have check that automatically creates these intermediate directories when attempting to symlink if they don't exist.

Not sure if the same limitation exists for cmd or powershell on windows as I do not use them personally.

I'm willing to put up a PR for this after the new year when I get some time if you don't beat me to it :)

**Comment by JanDeDobbeleer** [comment]
> It might be nice to have check that automatically creates these intermediate directories when attempting to symlink if they don't exist.

@boldandbrad while I could argue this goes beyond the scope of the project, I don't mind adding this but not as the default behaviour.
