### ISSUE TITLE
Some templates result in runtime errors

### ISSUE THREAD

**Issue by boldandbrad** [JanDeDobbeleer/aliae#229]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Consider an `aliae.yaml` containing the following:

```yaml
env:
  - name: XDG_CONFIG_HOME
    value: {{ .Home }}/.config
```

When sourced, the following error occurs:

```txt
aliae error:
Failed to parse config file: [16:13] could not find flow map content
  14 | env:
  15 |   - name: XDG_CONFIG_HOME
> 16 |     value: {{ .Home }}/.config
                   ^
```

I would expect aliae to expand the `{{ .Home }}` template into the path to `$HOME` as seen in the [docs](https://aliae.dev/docs/setup/templates#example).

This issue does not seem to be isolated to just `envs`, I've noticed the same problem using templates in `links` and other places.

In addition, it might be nice for aliae to "fail gracefully" when parsing errors like this occur, perhaps still running the rest of the config.

I'm using aliae version 0.26.0

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

**Comment by JanDeDobbeleer** [comment]
Try encapsulating this with quotes, I'm pretty sure this is a parser error and not aliae failing.

**Comment by boldandbrad** [comment]
Good call. Got it working by encapsulating the entire value in quotes:

```yaml
env:
  - name: XDG_CONFIG_HOME
    value: "{{ .Home }}/.config"
```

Might be good to update the docs to make it clear this is required for templates.

**Comment by JanDeDobbeleer** [comment]
Yup, it's related to the updated YAML library. Another small side effect.

**Comment by JanDeDobbeleer** [comment]
@boldandbrad actually, this is just YAML spec. When using an IDE to validate the YAML, your config will also report as invalid. I'll add that information to the docs nonetheless.
