### ISSUE TITLE
script installs incompatible version on WSL

### ISSUE THREAD

**Issue by cethien** [JanDeDobbeleer/aliae#24]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

when installing with`curl -s https://aliae.dev/install.sh | bash -s` on wsl, bash responds with
`/home/<user>/bin/aliae: line 1: Not: command not found`

tool works when building from source

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@cethien this seems to be an issue with the download (the executable isn't there, it's only an HTML page), I'll make the script more robust.
