### ISSUE TITLE
Alias not getting removed on Win10/pwsh

### ISSUE THREAD

**Issue by Lil-Dank** [JanDeDobbeleer/aliae#42]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The Alias I set using Aliae isn't getting removed after removing it from the .yaml configuration File.

I tried:
reloading the Powershell Profile

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@Lil-Dank did you restart the shell? Because the scope of this is Local which stays for as long as the shell is active. Restarting the shell (or starting a new instance) resolves that. I also just validated this locally. As this is PowerShell behaviour, this is according to design.
