### ISSUE TITLE
Existence check of command or file

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/aliae#64]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

```
{{ .CommandAvailable "some-command" }}
```
But this is a bit complicated because on bash it should be doing something like `command -v "$1" > /dev/null` 

```
{{ .FileExists "{{.Home}}/my-stuff" }}
```
Would be a simple `[ -e $1 ]`

**Comment by JanDeDobbeleer** [comment]
@trajano this is a duplicate request of #60

**Comment by trajano** [comment]
Oops
